/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package databaseproject;

import javax.swing.ButtonGroup;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Bashir Ebrahimi
 */
public class AddTeachers extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public AddTeachers() {
        initComponents();

        ButtonGroup bg = new ButtonGroup();
        bg.add(rbMale);
        bg.add(rbFemale);
        rbFemale.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtteacherid = new javax.swing.JTextField();
        txtTeacherName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTeahcerFName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbFemale = new javax.swing.JRadioButton();
        rbMale = new javax.swing.JRadioButton();
        btnResetTeacher = new javax.swing.JButton();
        btnAddTeacher = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtSubject = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtEducationlevel = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 50, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Teacher Registration Form");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_close_window_24px.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/backBtnW.png"))); // NOI18N
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("ID:");
        jLabel4.setToolTipText("");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtteacherid.setBackground(new java.awt.Color(255, 255, 255));
        txtteacherid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtteacherid.setForeground(new java.awt.Color(0, 102, 102));
        txtteacherid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtteacherid, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, -1));

        txtTeacherName.setBackground(new java.awt.Color(255, 255, 255));
        txtTeacherName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTeacherName.setForeground(new java.awt.Color(0, 102, 102));
        txtTeacherName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtTeacherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 260, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Name:");
        jLabel5.setToolTipText("");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        txtTeahcerFName.setBackground(new java.awt.Color(255, 255, 255));
        txtTeahcerFName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtTeahcerFName.setForeground(new java.awt.Color(0, 102, 102));
        txtTeahcerFName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtTeahcerFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 260, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("FatherName:");
        jLabel7.setToolTipText("");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Gender:");
        jLabel8.setToolTipText("");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        rbFemale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbFemale.setForeground(new java.awt.Color(0, 102, 102));
        rbFemale.setText("Female");
        jPanel2.add(rbFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        rbMale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbMale.setForeground(new java.awt.Color(0, 102, 102));
        rbMale.setText("Male");
        jPanel2.add(rbMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, -1));

        btnResetTeacher.setBackground(new java.awt.Color(255, 255, 255));
        btnResetTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnResetTeacher.setForeground(new java.awt.Color(0, 102, 102));
        btnResetTeacher.setText("Reset");
        btnResetTeacher.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        btnResetTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTeacherActionPerformed(evt);
            }
        });
        jPanel2.add(btnResetTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 140, 40));

        btnAddTeacher.setBackground(new java.awt.Color(255, 255, 255));
        btnAddTeacher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddTeacher.setForeground(new java.awt.Color(0, 102, 102));
        btnAddTeacher.setText("Add Teacher");
        btnAddTeacher.setToolTipText("");
        btnAddTeacher.setActionCommand("Add Teachers");
        btnAddTeacher.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 102, 102)));
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 140, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Address:");
        jLabel11.setToolTipText("");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        txtAddress.setBackground(new java.awt.Color(255, 255, 255));
        txtAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(0, 102, 102));
        txtAddress.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("DOB:");
        jLabel12.setToolTipText("");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        txtDOB.setBackground(new java.awt.Color(255, 255, 255));
        txtDOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtDOB.setForeground(new java.awt.Color(0, 102, 102));
        txtDOB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 260, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Contact:");
        jLabel13.setToolTipText("");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        txtContact.setBackground(new java.awt.Color(255, 255, 255));
        txtContact.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtContact.setForeground(new java.awt.Color(0, 102, 102));
        txtContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 260, -1));

        txtSalary.setBackground(new java.awt.Color(255, 255, 255));
        txtSalary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSalary.setForeground(new java.awt.Color(0, 102, 102));
        txtSalary.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 260, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 102));
        jLabel14.setText("Salary:");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtSubject.setBackground(new java.awt.Color(255, 255, 255));
        txtSubject.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSubject.setForeground(new java.awt.Color(0, 102, 102));
        txtSubject.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 260, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 102));
        jLabel15.setText("Subject:");
        jLabel15.setToolTipText("");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txtEducationlevel.setBackground(new java.awt.Color(255, 255, 255));
        txtEducationlevel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEducationlevel.setForeground(new java.awt.Color(0, 102, 102));
        txtEducationlevel.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtEducationlevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 260, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 102));
        jLabel16.setText("Education Level:");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtEmail.setBackground(new java.awt.Color(255, 255, 255));
        txtEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(0, 102, 102));
        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 102, 102)));
        jPanel2.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 260, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 102, 102));
        jLabel17.setText("Email:");
        jLabel17.setToolTipText("");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 440, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:

        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        new TeacherInfo().show();
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked
    int posX = 0, posY = 0;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        posX = evt.getX();
        posY = evt.getY();

    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        this.setLocation(evt.getXOnScreen() - posX, evt.getYOnScreen() - posY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:
        String id = txtteacherid.getText().trim();
        String name = txtTeacherName.getText().trim();
        String fName = txtTeahcerFName.getText().trim();
        String address = txtAddress.getText().trim();
        String educationlevel = txtEducationlevel.getText().trim();
        String subject = txtSubject.getText().trim();
        String salary = txtSalary.getText().trim();
        String DOB = txtDOB.getText().trim();
        String contact = txtContact.getText().trim();
        String email = txtEmail.getText().trim();

        String selectedGender = null;
        if (rbMale.isSelected()) {
            selectedGender = "Male";
        } else if (rbFemale.isSelected()) {
            selectedGender = "Female";
        }

        if (name.isEmpty() || fName.isEmpty() || email.isEmpty()) {
            JOptionPane.showMessageDialog(null, "All Fields are Required !");
        } else {
            String sql = "INSERT INTO teacher_tbl(Teacher_ID,teacnername,F_name,Address,educationLevel,Subject,Salary,DOB,gender,contact,email)"
                    + " VALUES(?,?,?,?,?,?,?,?,?,?,?)";
            try (Connection con = DatabaseConnection.getConnection(); PreparedStatement pstmt = con.prepareStatement(sql)) {
                pstmt.setString(1, id);
                pstmt.setString(2, name);
                pstmt.setString(3, fName);
                pstmt.setString(4, address);
                pstmt.setString(5, educationlevel);
                pstmt.setString(6, subject);
                pstmt.setString(7, salary);
                pstmt.setString(8, DOB);
                pstmt.setString(9, selectedGender);
                pstmt.setString(10, contact);
                pstmt.setString(11, email);

                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "Saved");

                txtteacherid.setText("");
                txtTeacherName.setText("");

            } catch (SQLException e) {
                System.err.print(e.getMessage());
            }
        }


    }//GEN-LAST:event_btnAddTeacherActionPerformed

    private void btnResetTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTeacherActionPerformed
        // TODO add your handling code here:
        txtteacherid.setText("");
        txtTeacherName.setText("");
    }//GEN-LAST:event_btnResetTeacherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTeachers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTeachers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnResetTeacher;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbFemale;
    private javax.swing.JRadioButton rbMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEducationlevel;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSubject;
    private javax.swing.JTextField txtTeacherName;
    private javax.swing.JTextField txtTeahcerFName;
    private javax.swing.JTextField txtteacherid;
    // End of variables declaration//GEN-END:variables
}
